### ISSUE TITLE
Enhance Issues expirience at Eclipse JNoSQL

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#339]
Hello everyone, we're working to centralize to put the Eclipse JNoSQL issues in a single repository on this current one. 

To make it possible, we have several tasks to do:

- [x] Create "good first issue" label
- [x] Move the issues from [driver](https://github.com/eclipse/jnosql-communication-driver/issues) to JNoSQL
- [x] Move the issues from [mapping](https://github.com/eclipse/jnosql-mapping-extension/issues) to JNoSQL
- [x] Disable driver issues to JNoSQL
- [x] Disable mapping issues to JNoSQL
- [ ] Put on the README documentation how to open an issue on all of three Eclipse JNoSQL repositories.

**Comment by viniciusbrg** [comment]
Hey @otaviojava is this still pending?

It seems that most of this issue is already done, we already have a 'good first issue' label, 

issues in the driver and mapping repositories are already disabled

About the README part, I'm confused, isn't the goal to open issues just on this repo? 

If that's the case and if we want to distinguish issues, we could have labels indicating the project that the issue belongs to.

**Comment by otaviojava** [comment]
Hey, @viniciusbrg, I've updated the tasks.

The goal is to centralize those issues into a single place.

**Comment by viniciusbrg** [comment]
Okay @otaviojava I got it

I can update our readme explaining that issues regarding the databases&extensions repository should be reported here
And then I can create a field in the bug & feature issue templates allowing the user to indicate which project this issue refers to (Jnosql, jnosql-extensions or jnosql-databases)

What do you think?

**Comment by otaviojava** [comment]
I like this.
Thanks
